title: Adventures of Masqueraded Huey
description: This is the website for the comic Adventures of Masqueraded Huey
twitter_username: Masquerade_Huey
github_username: stech6476
theme: jekyll-theme-cayman
